name: 'mypr-auto-labeler'
description: 'Automatically label new pull requests based on the paths and branch name'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/labeler.yml'
    required: false
  sync-labels:
    description: 'Whether or not to remove labels when matching files are reverted'
    default: false
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
